### ISSUE TITLE
error while compile project

### ISSUE THREAD

**Issue by why-scholar** [mhalber/Fine-To-Coarse-Registration#1]
when I compile the project, I got the following error:

 R3Mesh.cpp:(.text+0x9ca): undefined reference to `glBegin'
R3Mesh.cpp:(.text+0x9d7): undefined reference to `glVertex3dv'
R3Mesh.cpp:(.text+0x9e4): undefined reference to `glVertex3dv'
../gaps/lib/x86_64//libR3Shapes.a(R3Mesh.o): In function `R3Mesh::DrawEdges() const':
R3Mesh.cpp:(.text+0x242d): undefined reference to `glBegin'
R3Mesh.cpp:(.text+0x243a): undefined reference to `glVertex3dv'
R3Mesh.cpp:(.text+0x2447): undefined reference to `glVertex3dv'
R3Mesh.cpp:(.text+0x244c): undefined reference to `glEnd'
../gaps/lib/x86_64//libR3Shapes.a(R3Mesh.o): In function `R3Mesh::DrawEdgeIDs() const':
R3Mesh.cpp:(.text+0x24a8): undefined reference to `glDisable'
R3Mesh.cpp:(.text+0x24c5): undefined reference to `glBegin'
R3Mesh.cpp:(.text+0x24d2): undefined reference to `glVertex3dv'
R3Mesh.cpp:(.text+0x24df): undefined reference to `glVertex3dv'
R3Mesh.cpp:(.text+0x24e4): undefined reference to `glEnd'
R3Mesh.cpp:(.text+0x24f5): undefined reference to `glColor3ub'
../gaps/lib/x86_64//libR3Shapes.a(R3Mesh.o): In function `R3Mesh::DrawVertexIDs() const':
R3Mesh.cpp:(.text+0x2672): undefined reference to `glDisable'
R3Mesh.cpp:(.text+0x26d7): undefined reference to `glColor3ub'
R3Mesh.cpp:(.text+0x2716): undefined reference to `glEnable'
../gaps/lib/x86_64//libR3Shapes.a(R3Mesh.o): In function `R3Mesh::DrawFaces() const':
R3Mesh.cpp:(.text+0x378d): undefined reference to `glNormal3dv'
R3Mesh.cpp:(.text+0x379a): undefined reference to `glVertex3dv'
R3Mesh.cpp:(.text+0x37a7): undefined reference to `glVertex3dv'
R3Mesh.cpp:(.text+0x37b4): undefined reference to `glVertex3dv'
R3Mesh.cpp:(.text+0x37b9): undefined reference to `glEnd'
R3Mesh.cpp:(.text+0x37e4): undefined reference to `glBegin'
../gaps/lib/x86_64//libR3Shapes.a(R3Mesh.o): In function `R3Mesh::DrawFaceIDs() const':

the gaps project is successfully compiled.

How does this situation occurs?

**Comment by mhalber** [comment]
It appears that the project is unable to link correctly against OpenGL. Could you let me know what is your operating system?  Specifically if you type the 'uname -s' into your terminal, what is the output?

**Comment by why-scholar** [comment]
The operation system is ubuntu  16.04 x64.  For dependencies, lib file of glfw3 is installed in the directory "/usr/local/lib", lib files of glew are installed in the directory "/usr/local/lib64". The including folder of glfw3 is installed in the directory "/usr/local/include/GLFW"， the including folder of glew is installed in the  directory "/usr/local/include/GL". 

The  "/usr/local/lib64" directory contains following files:
libGLEW.a  libGLEW.so  libGLEW.so.2.0  libGLEW.so.2.0.0

The "/usr/local/include/GL" contains following files:
glew.h  glxew.h  wglew.h

I have modified the makefile in fetregister folder to indicate the directories of including folder and library of glew. 
`# Useful Directories
  BIN_DIR = ../bin/

  #LIB_DIR = /usr/local/lib/

  LIB_DIR = /usr/local/lib64/

 CPPFLAGS += -I. -I/usr/local/include -I/usr/local/include/GL -I../              $(IMGUI_DIR) -I../$(BSC_DIR) -I../$(GAPS_DIR)pkgs -DRN_USE_CSPARSE -            DRN_USE_SPLM -DNDEBUG
`

**Comment by mhalber** [comment]
If you're saying that the glfw3 is installed under /usr/local/lib, while glew is under /usr/local/lib64 then you need to set the -L flags under LIBS variable correctly. Could you attach your makefile? 
Secondly, don't add the GL folder to your include dir. Source code will attempt to include "GL/<header_name>.h" files.

**Comment by why-scholar** [comment]
@mhalber. Thanks for your reply. 

I have solved these problems. The reason for these errors is that the library depending on other libraries must locate in front of their depending libraries in the makefile.

**Comment by mhalber** [comment]
Glad to see it resolved. I will close the issue then.
