### ISSUE TITLE
error while compile project with make USE_WINDOW=1

### ISSUE THREAD

**Issue by HollisJoe** [mhalber/Fine-To-Coarse-Registration#2]
Hi, When I compile use make -C fetregister USE_WINDOW=1.
g++ -O3 -g0 -std=c++11 -pthread -Wall -Wno-#warnings -Wno-sign-compare  -I. -I/usr/include -I/usr/local/include -I../basics/third_party/imgui/ -I../basics/ -I../gaps/pkgs -DRN_USE_CSPARSE -DRN_USE_SPLM -DNDEBUG -DFETREGISTER_USE_WINDOW -c fetregister.cpp -o ../out/fetregister.o
In file included from ../basics/basics.h:70:0,
                 from common.h:45,
                 from fetregister.cpp:34:
/usr/local/include/GLFW/glfw3.h:159:28: fatal error: GL/glcorearb.h: cannot find the file or directory
   #include <GL/glcorearb.h>
                            ^
compilation terminated.
What is the problem? Thank you!

**Comment by mhalber** [comment]
Hi, thanks for submitting the issue. We clearly have more compilation issues than I'd like to see. Could you please let me know your operating system?

It seems like the compiler is not able to find the glcorearb.h header. I'd double check your include paths. If it is not present in your GL folder, then again, please let me know your configuration. glcorearb.h can be also found here: https://www.khronos.org/registry/OpenGL/api/GL/glcorearb.h

**Comment by HollisJoe** [comment]
My operating system is Ubuntu 14.04, Success compile use make -C fetregister, and I cannot find the  glcorearb.h header,  I download from https://www.khronos.org/registry/OpenGL/api/GL/glcorearb.h, and copy to the GL folder. and  compile use make -C fetregister USE_WINDOW=1. It has the error:
io.h:450:61: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]
                     &m[0][2], &m[1][2], &m[2][2], &m[3][2] );
                                                             ^
At global scope:
cc1plus: warning: unrecognized command line option "-Wno-#warnings" [enabled by default]
make: *** [../out/fetregister.o] error 1
make: leave the directory “/home/xdsf/source/Fine-To-Coarse-Registration/Fine-To-Coarse-Registration-master/fetregister”
What is the problem? Thank you!

**Comment by HollisJoe** [comment]
rendering.h: In function ‘void rendering::init_framebuffer(RenderingState*, bsc::vec4i)’:
rendering.h:1133:96: error: ‘glDeleteFramebuffers’ was not declared in this scope
   if(!render->fullscreen_framebuffer) { glDeleteFramebuffers(1, &render->fullscreen_framebuffer); }
                                                                                                ^
rendering.h:1136:89: error: ‘glDeleteRenderbuffers’ was not declared in this scope
   if(!render->depth_renderbuffer) { glDeleteRenderbuffers(1, &render->depth_renderbuffer); }
                                                                                         ^
rendering.h:1138:56: error: ‘glGenFramebuffers’ was not declared in this scope
   glGenFramebuffers(1, &render->fullscreen_framebuffer );
                                                        ^
rendering.h:1141:54: error: ‘glGenRenderbuffers’ was not declared in this scope
   glGenRenderbuffers( 1, &render->depth_renderbuffer );
                                                      ^
rendering.h:1143:69: error: ‘glBindFramebuffer’ was not declared in this scope
   glBindFramebuffer( GL_FRAMEBUFFER, render->fullscreen_framebuffer );
                                                                     ^
rendering.h:1150:87: error: ‘glFramebufferTexture’ was not declared in this scope
   glFramebufferTexture( GL_FRAMEBUFFER, GL_COLOR_ATTACHMENT0, render->color_buffer, 0 );
                                                                                       ^
rendering.h:1161:31: error: ‘glDrawBuffers’ was not declared in this scope
   glDrawBuffers(2, attachments);
                               ^
rendering.h:1164:65: error: ‘glBindRenderbuffer’ was not declared in this scope
   glBindRenderbuffer(GL_RENDERBUFFER, render->depth_renderbuffer);
                                                                 ^
rendering.h:1165:67: error: ‘glRenderbufferStorage’ was not declared in this scope
   glRenderbufferStorage(GL_RENDERBUFFER, GL_DEPTH_COMPONENT, w, h );
                                                                   ^
rendering.h:1166:109: error: ‘glFramebufferRenderbuffer’ was not declared in this scope
   glFramebufferRenderbuffer(GL_FRAMEBUFFER, GL_DEPTH_ATTACHMENT, GL_RENDERBUFFER, render->depth_renderbuffer);
                                                                                                             ^
rendering.h:1168:46: error: ‘glCheckFramebufferStatus’ was not declared in this scope
   if (glCheckFramebufferStatus(GL_FRAMEBUFFER) != GL_FRAMEBUFFER_COMPLETE)
                                              ^
In file included from fetregister.cpp:44:0:
gui.h: In function ‘i32 gui::fps(bsc::vec4i, SequenceData*, ViewOptions*, i64)’:
gui.h:404:57: warning: format ‘%lld’ expects argument of type ‘long long int’, but argument 3 has type ‘i64 {aka long int}’ [-Wformat=]
   sprintf( n_points_string, "NPoints  : %lld", n_points );
                                                         ^
fetregister.cpp: In function ‘void Display()’:
fetregister.cpp:539:73: error: ‘glBindFramebuffer’ was not declared in this scope
     glBindFramebuffer(GL_READ_FRAMEBUFFER, render.fullscreen_framebuffer);
                                                                         ^
fetregister.cpp:717:18: error: ‘struct Options’ has no member named ‘xforms_history_filename’
         if( opts.xforms_history_filename )
                  ^
fetregister.cpp:719:11: error: ‘write_transformation_history’ is not a member of ‘io’
           io::write_transformation_history( opts.xforms_history_filename,
           ^
fetregister.cpp:719:50: error: ‘struct Options’ has no member named ‘xforms_history_filename’
           io::write_transformation_history( opts.xforms_history_filename,

**Comment by mhalber** [comment]
Hi, thanks for these issues again. I have only tested linux building in a server setting, hence never using a window. Clearly blunder on my part. I've also forgot that on linux the library order matters. Pushed some changes to fix that and other minor issues. Currently it builds on elementaryOs (linux distro on top of Ubuntu 16.04 LTS), as I currently don't have access to clear Ubuntu machine.

Let me know, if new fix works. Note that it assumes you're linking against the static glfw3.

**Comment by HollisJoe** [comment]
Hi, thanks.
fetregister.cpp:717:18: error: ‘struct Options’ has no member named ‘xforms_history_filename’
if( opts.xforms_history_filename )
^
fetregister.cpp:719:11: error: ‘write_transformation_history’ is not a member of ‘io’
io::write_transformation_history( opts.xforms_history_filename,

What this error? Thank You

**Comment by mhalber** [comment]
Hi - this error was due to me leaving old testing code in there. New update removes this line - you should not see this error anymore.

**Comment by HollisJoe** [comment]
Yes,  Thanks very much.
