### ISSUE TITLE
question about .fcb file

### ISSUE THREAD

**Issue by why-scholar** [mhalber/Fine-To-Coarse-Registration#3]
@mhalber 
In the project website, all information introducing  .fcb file is only the following sentence:
"Feature files (.fcb) are sets of preprocessed RGB-D frames put into a single file. We provide them for the ease of experimentation with our system. Our code also provides conf2fet program that is able to produce a fet file from a configuration file."  
However, it is not enough for us to understand the fcb file. Could you provide more introduction about .fcn file? Thanks.

In addition, is there a way to display the extracted structure features, such as plane and Silhouette?

**Comment by mhalber** [comment]
Hi, thank you for the issue. The fcb files are representation for FETReconstruction class found in gaps/pkgs/FET. I guess I can create a better write-up on fcb files in near future, but it would be useful to know what information you are exactly looking for.

As far as visualization go, the view tab has a plenty of visualization options available. For what you're asking there is a feature display mode options - there is rgb, feature_id, normals and phong shading. Feature_id color scheme is explained in vs_pointcloud source code in rendering.h. See screenshot for the display mode slider.

![feat_disp_mode](https://cloud.githubusercontent.com/assets/6202456/25813304/0887ee1e-33e7-11e7-92ff-74f566ec3dcb.png)

**Comment by why-scholar** [comment]
@mhalber 

Thanks for your reply.  I have two questions.

The first question is which paper do you refer to extract geometric features sucn as plane,  silhouette, ridge and valley. The codes in gaps/pkgs/FET do not indicate the reference papers, although the cvpr paper gives a reference list:
"
We have experimented with a number of feature types, including SIFT and Harris corners in both
color and depth images. However, we have ultimately found planar patches [3, 10, 11, 12, 25, 29, 31, 35,
39, 41, 43] and linear edges along creases and contours in depth images [52] to be most robust.
"

The second question is that the code dose not provide us with visualization application. After compilation, we only get two executable files: conf2fet and fetregistration. How could I get the visualization application?

**Comment by mhalber** [comment]
Hi again, 

As far as the extracting geometric features, in the paper we list the publications that used such type of a feature, as we do not want to claim a contribution in this space. That being said we do not exactly implement any existing solution, rather we came up with an algorithm that worked for us here. So I can't point you to a specific paper here. conf2fet provides implementation that we created and used.

Secondly the fetregister, if compiled using command
~~~~~
make USE_WINDOW=1
~~~~~
Then running 
~~~~~
fetregister fet/5_0.05.fcb hv_c11_2_initial.conf -v
~~~~~
in the respective folder(provided fetregister is in search path) should create a interface like the one in the screenshot above. Is it not the case for you? I

**Comment by why-scholar** [comment]
@mhalber 

Thanks very much. There are some errors when compiling under "USE_WINDOW=1" condition. Anyway , Thank you again.

**Comment by mhalber** [comment]
I've pushed an update to bulid the fetregister under linux with "USE_WINDOW=1". Please check if this helps you. If not, could you open new issue?

**Comment by why-scholar** [comment]
Hi,

I have compile the code under linux with "USE_WINDOW=1". Thanks very much.

In addition, is there any documents about gaps package? The code is hard for me to understand, and the documents will make me better to understand the paper. 

Thanks again!

2017-05-13 

why_scholar 



发件人：Maciej Halber <notifications@github.com>
发送时间：2017-05-10 22:23
主题：Re: [mhalber/Fine-To-Coarse-Registration] question about .fcb file (#3)
收件人："mhalber/Fine-To-Coarse-Registration"<Fine-To-Coarse-Registration@noreply.github.com>
抄送："why-scholar"<why_scholar@126.com>,"Author"<author@noreply.github.com>

I've pushed an update to bulid the fetregister under linux with "USE_WINDOW=1". Please check if these help you. If not, could you open new issue?

**Comment by mhalber** [comment]
Gaps is a package written by prof. Thomas Funkhouser, hosted here: https://github.com/tomfunkhouser/gaps

As far as I know there is no documentation, other than just reading the code and comments within.

**Comment by why-scholar** [comment]
Ok！ Thanks very much!

2017-05-17 

why_scholar 



发件人：Maciej Halber <notifications@github.com>
发送时间：2017-05-17 03:11
主题：Re: [mhalber/Fine-To-Coarse-Registration] question about .fcb file (#3)
收件人："mhalber/Fine-To-Coarse-Registration"<Fine-To-Coarse-Registration@noreply.github.com>
抄送："why-scholar"<why_scholar@126.com>,"Author"<author@noreply.github.com>

Gaps is a package written by prof. Thomas Funkhouser, hosted here: https://github.com/tomfunkhouser/gaps
As far as I know there is no documentation, other than just reading the code and comments within.
