### ISSUE TITLE
Could not create glfw window?

### ISSUE THREAD

**Issue by qzhou711** [mhalber/Fine-To-Coarse-Registration#4]
hi, when i try to run  `./fetregister ../harvard_c11/fet/5_0.05.fcb ../harvard_c11/hv_c11_2_initial.conf -v`
then output msg "Could not create glfw window Window not created, terminating!"
anyone can help me?Thanks a lot.

**Comment by mhalber** [comment]
This message emitted when glfw library (opengl window creation) is unable to create window with proper OpenGL support - the context version we require is opengl 4.1.
Does your system support that?

**Comment by qzhou711** [comment]
Thanks a lot for your reply!

Qiang

2018-04-04 23:04 GMT+08:00 Maciej Halber <notifications@github.com>:
